name: Build and Deploy Yarn Project

# 触发条件：当代码推送到 main 分支时触发
on:
  push:
    branches:
      - main
  workflow_dispatch: # 支持手动触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 虚拟机

    steps:
      # 步骤 1：检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 步骤 2：设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # 根据项目需要选择 Node.js 版本
          cache: 'yarn' # 缓存 Yarn 依赖以加速构建

      # 步骤 3：安装 Yarn 依赖
      - name: Install dependencies
        run: yarn install

      # 步骤 4：构建项目
      - name: Build project
        run: yarn build # 替换为你的构建命令，如 yarn run build:prod

      # 步骤 5：部署到云服务器
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote-user: ${{ secrets.REMOTE_USER }}
          server-ip: ${{ secrets.REMOTE_HOST }}
          remote-path: ${{ secrets.TARGET_PATH }}
          local-path: dist
          args: '-avzr --delete'

